### ISSUE TITLE
Better Stats has visual errors.

### ISSUE THREAD

**Issue by EpicOverKill567** [tiffit/Wynnforge#6]
It is set up for people to use with a small GUI, which makes everything else just way too small. Please try to set it up for normal GUI as it looks great.

**Comment by tiffit** [comment]
Can you take a screenshot? I want to see how exactly I need to change it.

**Comment by EpicOverKill567** [comment]
https://i.gyazo.com/e0d97b4ae94b53d6ffe7edf0be97c554.png
This is what it looks like on a normal GUI Scale
https://i.gyazo.com/02f3f246ab69377808319c8621bbb4a1.png
And this is it on a small, I don't know if this is a problem only for me
but I would love to be able to use this as on small GUI it looks great just
everything else is so tiny.

**Comment by tiffit** [comment]
Try out update 0.3.1 and see if the issue is fixed

**Comment by EpicOverKill567** [comment]
Sorry it took so long to reply, that fixed it thanks a lot!
